from sqlalchemy import Column, Integer, String, DateTime, Boolean, SmallInteger, DECIMAL, ForeignKey
from sqlalchemy.dialects.mssql import VARCHAR, NVARCHAR, BIT, CHAR
from sqlalchemy.orm import relationship
from app.utils.db import db

class Usuario(db.Model):
    __tablename__ = 'USUARIOS'
    __table_args__ = {'schema': 'HelpPeople'}

    USR_LOGIN = Column(VARCHAR(30), primary_key=True, nullable=False)
    USR_CARNET_ID = Column(VARCHAR(50), nullable=True)
    USR_NOM = Column(VARCHAR(60), nullable=False)
    USR_APE = Column(VARCHAR(60), nullable=False)
    USR_PASSWD = Column(VARCHAR(50), nullable=True)
    USR_TEL = Column(VARCHAR(40), nullable=True)
    USR_EXT = Column(VARCHAR(6), nullable=True)
    USR_OFICINA = Column(VARCHAR(50), nullable=True)
    USR_FOTO = Column(VARCHAR(200), nullable=True)
    USR_UBICACION = Column(VARCHAR(50), nullable=True)
    USR_MAIL = Column(VARCHAR(200), nullable=True)
    TIPO_COD = Column(Integer, nullable=True)    
    CAR_COD = Column(Integer, nullable=True)
    USR_FECING = Column(DateTime, nullable=True)
    DEP_COD = Column(VARCHAR(50), nullable=True)
    USR_SEXO = Column(VARCHAR(15), nullable=True)
    USR_CEL = Column(VARCHAR(15), nullable=True)
    ESTU_COD = Column(Integer, nullable=True)
    NIVU_COD = Column(Integer, nullable=True)
    UBI_COD = Column(Integer, nullable=True)
    USR_SUPER = Column(Integer, nullable=True)
    USR_TEL2 = Column(VARCHAR(10), nullable=True)
    HORAS_MES = Column(DECIMAL(18, 0), nullable=True)
    VALOR_HORA = Column(DECIMAL(18, 0), nullable=True)
    CentroCostos = Column(VARCHAR(200), nullable=True)
    USR_EMPRESA = Column(VARCHAR(200), nullable=True)
    pais = Column(VARCHAR(100), nullable=True)
    dpto = Column(VARCHAR(100), nullable=True)
    ciudad = Column(VARCHAR(100), nullable=True)
    HOR_COD = Column(Integer, nullable=True)
    USR_EXTERNO = Column(Integer, nullable=False, default=0)
    ACTIVAR_SQLDINAMICO = Column(VARCHAR(2), nullable=True)
    USR_VIP = Column(SmallInteger, nullable=True, default=0)
    FECHA_ACTUALIZA = Column(DateTime, nullable=True)
    USR_ACTUALIZA = Column(VARCHAR(30), nullable=True)
    TIPO_DOC = Column(Integer, nullable=True)
    NUM_DOC = Column(VARCHAR(50), nullable=True)
    SESION_ACTIVA = Column(BIT, nullable=True, default=False)
    SEDE_COD = Column(Integer, nullable=True)
    TORRE_COD = Column(Integer, nullable=True)
    PISO_COD = Column(Integer, nullable=True)
    USR_DIRECCION = Column(VARCHAR(300), nullable=True, default='')
    USR_VERIFICATION_SEGURIDAD = Column(VARCHAR(10), nullable=True)
    USR_TIPO_VERIFICATION = Column(VARCHAR(10), nullable=True)
    USR_VERIFICATION_MAIL = Column(VARCHAR(100), nullable=True)
    USR_VERIFICATION_CEL = Column(VARCHAR(20), nullable=True)
    USR_VERIFICATION_INDICATIVO = Column(VARCHAR(10), nullable=True)
    directoryId = Column(Integer, nullable=True)
    codigoRegion = Column(Integer, nullable=True)
    codigoSucursal = Column(Integer, nullable=True)
    CodZonaHoraria = Column(Integer, nullable=True)
    USR_AUTHENTICATION = Column(Integer, nullable=True)
    USR_LOGIN_MAIL = Column(VARCHAR(800), nullable=True)
    USR_SADE = Column(NVARCHAR(255), nullable=True)
    USR_TIPO_DOCUMENTO = Column(Integer, nullable=True)
    USR_DOCUMENTO = Column(NVARCHAR(255), nullable=True)
    USR_EMAIL2 = Column(NVARCHAR(255), nullable=True)
    USR_LANG = Column(VARCHAR(5), nullable=True)
    USR_CONTRIBUYENTE = Column(BIT, nullable=False, default=False) 
    USR_LANG = Column(VARCHAR(5), nullable=True)

 
class Solicitud(db.Model):
    __tablename__ = 'SOLICITUD'
    __table_args__ = {'schema': 'HelpPeople'}

    # Columnas existentes en la base de datos
    sol_cod = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    usr_login = Column(VARCHAR(30), ForeignKey('USUARIOS.USR_LOGIN', onupdate="CASCADE"), nullable=True)
    sol_recibidapor = Column(VARCHAR(30), nullable=True)
    sol_fecha = Column(DateTime, nullable=True)
    sol_hora = Column(DateTime, nullable=True)
    sol_descripcion = Column(NVARCHAR, nullable=True)
    pri_cod = Column(Integer, nullable=True)  
    med_cod = Column(Integer, nullable=True)
    est_cod = Column(Integer, nullable=True)
    sol_titulo = Column(VARCHAR(500), nullable=True)
    sol_anombrede = Column(VARCHAR(30), nullable=True)
    equ_nombre = Column(VARCHAR(50), nullable=True)
    sol_llamada = Column(Integer, nullable=True)
    sol_fecha_cierre = Column(DateTime, nullable=True)
    sol_fecha_venci = Column(DateTime, nullable=True)
    sol_p_encuesta = Column(Integer, nullable=True)
    sol_atrazada = Column(Integer, nullable=True)
    sol_reabierta = Column(VARCHAR(1), nullable=True)
    sol_asignada = Column(VARCHAR(1), nullable=True)
    sol_fecha_radica = Column(DateTime, nullable=True)
    sol_tipo = Column(VARCHAR(50), nullable=True)
    tipo_nat = Column(NVARCHAR(50), nullable=True)
    sla_cod = Column(Integer, nullable=True)
    tip_err = Column(NVARCHAR(50), nullable=True)
    provocado = Column(Integer, nullable=True)
    cvence = Column(VARCHAR(1), nullable=True)
    sol_fecha_expectativa = Column(DateTime, nullable=True)
    sol_incidente_mayor = Column(VARCHAR(5), nullable=True)
    sol_fecha_recepcion = Column(DateTime, nullable=True)
    sol_fecha_reapertura = Column(DateTime, nullable=True)
    sol_mal_escalado = Column(BIT, nullable=True, default=0)
    sol_asunto = Column(NVARCHAR, nullable=True)
    sol_vip = Column(Integer, nullable=True, default=0)
    tprob_cod = Column(Integer, nullable=True)
    catalogo_usu_path = Column(NVARCHAR(500), nullable=True)
    cod_nat = Column(VARCHAR(10), nullable=True)
    formulario_usuario_direccion = Column(VARCHAR(300), nullable=True, default='')
    sol_descripcion_texto_plano = Column(NVARCHAR, nullable=True, default='')
    fecha_modificacion = Column(DateTime, nullable=True, default=None)
    es_incidente_mayor = Column(BIT, nullable=True, default=0)

class OrdenTrabajo(db.Model):
    __tablename__ = 'ORDEN_TRABAJO'
    __table_args__ = {'schema': 'HelpPeople'}
    ORT_COD = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    ORS_COD = Column(Integer, ForeignKey('ORDEN_SERVICIO.ORS_COD', onupdate="CASCADE"), nullable = False)
    ORT_DESCRIPCION = Column(NVARCHAR(max), nullable=True)
    PRO_COD = Column(Integer, nullable=True)
    ORT_PORCENTAJE = Column(Integer, nullable = True)
    ORT_COMENTARIO =Column(VARCHAR (100), nullable = True)
    ORT_SOLUCION = Column(NVARCHAR(max), nullable = True)
    ORT_RECOMENDACIONES	 = Column (VARCHAR (100), nullable=True)
    ORT_FECHAACEP = Column(DateTime, nullable=True)	
    ORT_FECINI = Column(DateTime, nullable = True)
    ORT_FECFIN = Column (DateTime, nullable = True)
    ORT_HORAINI	= Column (DateTime, nullable = True)
    ORT_HORAFIN = Column (DateTime, nullable = True),
    EST_COD = Column(Integer, nullable=True)
    USR_RESPONSABLE =Column(VARCHAR (30), nullable = True)
    ORT_NUEVA = Column(Integer, nullable = True)
    ORT_TIEMPORESOL = Column(VARCHAR (50), nullable = True)
    ORT_GUARDARSOL = Column(CHAR (2), nullable = True)
    ORT_DEVUELTA = Column(CHAR (1), nullable = True)
    ORT_ATENDIDA = Column(Integer, nullable= True, default=0)
    Medio = Column(NVARCHAR (50), nullable = True)
    T_ATENCION = Column(DECIMAL, nullable=True)
    T_AVANCE_ORT = Column(VARCHAR (20), nullable = True, default = '0')
    ORT_PRIMERA_LLAMADA = Column(BIT, nullable = True, default= 0)
    ORT_PRIMERA_ORDEN = Column(BIT, nullable=True, default = 0)
    ORT_OPCIONAL = Column(VARCHAR(100),nullable=True, default='')
    ORT_TIPO_CIERRE = Column(Integer, nullable=True)
    GRUP_COD = Column(Integer,nullable=True)
    ORT_FECHA_CIERRE = Column(DateTime, nullable=True)
    PREDECESORA = Column(Integer, nullable=True)
    PLAN_COD = Column(Integer, nullable=True)
    GRUP_CONFIRM = Column(BIT, nullable = True)
    AVANCE = Column(Integer, nullable=True, default= 0)
    PRECEDE = Column(Integer,nullable=True)
    COORDENADA_LATITUD = Column(VARCHAR(500),nullable=True, default = '')
    COORDENADA_LONGITUD = Column(VARCHAR(500),nullable=True, default = '')
    ORT_SOLUCION_TEXTO_PLANO = Column(NVARCHAR(max),nullable=True, default = '')
    PRIVADA = Column(BIT, nullable=True)
    flujoPosicion = Column(SmallInteger,nullable=True, default= 0)
    esReasignada = Column(BIT, nullable =True, default = 0)
    ORT_DESCRIPCION_TEXTO_PLANO = Column(NVARCHAR(max), nullable=True)
    ORT_FECHA_CREACION = Column(DateTime, nullable=True)
    CANT_SOLICITUDES_IA = Column(Integer, nullable=True)
    TOKENS_ENTRADA = Column(Integer,nullable=True)
    TOKENS_SALIDA = Column(Integer, nullable= True)

class OrdenServicio(db.Model):
    __tablename__ = 'ORDEN_SERVICIO'
    __table_args__ = {'schema': 'HelpPeople'}

    ORS_COD = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    SOL_COD = Column(Integer,nullable=False )
    USR_LOGIN = Column(VARCHAR(30),nullable= True)
    PROB_COD = Column(Integer, nullable=True)
    ORS_FECHA_ASIG = Column(DateTime, nullable=True)
    ORS_HORA_ASIG = Column(DateTime, nullable=True)
    ORS_FECHA_CIE = Column(DateTime, nullable=True)
    CAS_COD = Column(Integer, nullable=True)
    PRI_COD = Column(Integer, nullable=True)
    EST_O_COD = Column(Integer, nullable=True)
    ORS_PROCENTAJE = Column(Integer, nullable=True)
    ORS_FECTENTATIV = Column(DateTime, nullable=True)
    ORS_TIEMPOESTI = Column(Integer, nullable=True)
    ORS_DESCRIPCION = Column(VARCHAR(max), nullable=True)
    ORS_NUEVA = Column(Integer, nullable=True)
    ORS_ENCUESTA = Column(Integer, nullable=True)
    ORS_DEVUELTA = Column(VARCHAR(1), nullable=True)
    ORS_ACEPTADA_TEC = Column(Integer, nullable=True)
    severidad_COD = Column(Integer,nullable=True)
    impacto_cod = Column(Integer,nullable=True)
    urgencia_cod = Column(Integer,nullable=True)
    ESP_COD = Column(Integer,nullable=True)
    nroPlantilla = Column(Integer,nullable=True)
    eficaz = Column(VARCHAR(1), nullable=True, default='n')
    ORT_PRIMERA_ORDEN = Column(BIT, nullable=True)
    ORS_TIEMPO_ATRASO = Column(Integer,nullable=True, default='0')
    GRUP_COD = Column(Integer, nullable=True)
    CAS_COD_INICIAL = Column(SmallInteger, nullable=True)
    PROD_COD_INICIAL = Column(SmallInteger,nullable=True)
    MARCA_RECATEGORIZAR = Column(BIT, nullable=True)
    PROB_COD_INICIAL = Column(SmallInteger,nullable=True)
    ors_Asignada_prop = Column(Integer,nullable=True,default='0')
    VIP = Column(SmallInteger,nullable=True)
    TPROB_COD = Column(Integer, nullable=True)
    sprintId = Column(Integer,nullable=True)

